name: bkm
favicon: null
layout_spectrum: 0.34315172117203474
typography_spectrum: 0.9474157015793025
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7696539347525686
  lightness: 0.11000269930809736
  saturation: 0.5227531038690358
  rhythmicContrast: 0.22817792231217027
purpose: []
